title: ''
author: Evgenii Nikitin
email: ''
description: >- # this means to ignore newlines until "baseurl:"
  Blog about Drupal and related things.
baseurl: "" # the subpath of your site, e.g. /blog
domain: "https://www.enik.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass

plainwhite:
  tagline: ''
  date_format: "%b %-d, %Y"
  sitemap: false

  social_links:
    drupal: u/sinn
    linkedIn: in/nikitinevgeny

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-seo-tag
  - jekyll-gist

# jekyll-multiple-languages-plugin settings.
languages: ["en", "ru"]
exclude_from_localizations: ["javascript", "images", "css", "assets"]

# jekyll-seo-tag settings.
canonical_url: 'https://www.enik.io'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - build.sh
  - README.md
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
